version: '4.1'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "export NODE_ENV=production &&
       yarn install --frozen-lockfile --production=false &&
       yarn payload migrate &&
       yarn build &&
       yarn start"
    env_file:
      - .env
    environment:
      NODE_ENV: production
