services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-payload-app:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=1024" 
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2g
        reservations:
          cpus: '0.5'
          memory: 1g
    volumes:
      - media_storage:/app/public/media

volumes:
  media_storage:
