version: '4.2'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-payload-app:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
